#####################################
#                                   #
#  HADDOCK2.4 tools makefile        #
#                                   #
#####################################

all:
	cd tools;make
	   
clean:
	cd tools;make clean

dist:
	\rm Haddock/*.pyc Haddock/*/*.pyc; cd ..; tar cvfz haddock2.4.tgz haddock2.4/INSTALLATION haddock2.4/LICENSE haddock2.4/Makefile haddock2.4/README.md haddock2.4/CHANGES haddock2.4/config* haddock2.4/install.csh haddock2.4/haddock_configure.* haddock2.4/CGtools haddock2.4/DANItools haddock2.4/EMtools haddock2.4/RDCtools haddock2.4/Haddock haddock2.4/cgi haddock2.4/cns1.3 haddock2.4/doc haddock2.4/protocols haddock2.4/protocols-mtsl haddock2.4/tools haddock2.4/toppar
