# FROM ubuntu:16.04
# FROM phusion/baseimage:0.9.16
FROM mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu16.04

ENV DEBIAN_FRONTEND noninteractive
USER root

WORKDIR /root

## global env
ENV HOME=/root TERM=xterm

## set proper timezone
# RUN echo America/New_York > /etc/timezone && sudo dpkg-reconfigure --frontend noninteractive tzdata

## Install essential for building
    # software-properties-common \
RUN apt-get update && \
    apt-get install -y \
        build-essential \
        git \
        cmake \
        wget \
        flex \
        sudo \
        gfortran \
        python-pip \
        python2.7 \
        python2.7-dev

## Change bash Shell to tcsh
RUN sudo apt-get install tcsh && \
    chsh -s /bin/tcsh
    # chsh -s /usr/bin/tcsh
SHELL ["/bin/tcsh", "-c"]

## Install CNSsolve (http://cns-online.org/v1.3/)
COPY cns_solve_1.3_all_intel-mac_linux.tar.gz /software/

## Install HADDOCK (https://www.bonvinlab.org/software/haddock2.4/installation/)
COPY haddock2.4-2021-01.tgz /software/

## re-Make CNS with HADDOCK
RUN setenv PFX $HOME/haddock && \
    setenv CNS $PFX/cns_solve && \
    mkdir -p $CNS && \
    tar -C $CNS --strip-components=1 -xzf /software/cns_solve_1.3_all_intel-mac_linux.tar.gz && \
    tar -C $PFX -xzf /software/haddock2.4-2021-01.tgz && \
    pushd $CNS && \
    sed -i.BACK -e "s|_CNSsolve_location_|$CNS|g" cns_solve_env && \
    cp -a $PFX/haddock2.4-2021-01/cns1.3/* source && \
    make install && \
    popd


## Copy config file
COPY local_config_file $HOME/haddock/haddock2.4-2021-01/

## Rename date/time dependent cns_solve-0000000000.exe
RUN cd $HOME/haddock/cns_solve/intel-x86_64bit-linux/source && \
    find . -type f -name 'cns_solve*.exe' -exec sh -c 'x="{}"; mv "$x" "cns_solve.exe"' \;

## Configure HADDOCK
RUN cd $HOME/haddock/haddock2.4-2021-01 && \
    ./install.csh local_config_file
    #&& \
    #source ./haddock_configure.csh

## Mimic haddock_configure.csh task
# ENV HADDOCK $HOME/haddock/haddock2.4-2021-01
# ENV HADDOCKTOOLS $HADDOCK/tools
# ENV PYTHONPATH ${HADDOCK}
# RUN alias haddock2.4 `which python` $HADDOCK/Haddock/RunHaddock.py
# ENV NACCESS `which naccess`
# ENV PALES `which pales`
# ENV PROFIT `which profit`
# ENV TENSOR2 `which tensor2`

## Grant execution permissions to entire dir
RUN sudo chmod -R 777 $home

## Fix Symlink issue to QueueSubmit.py
RUN cd $HOME/haddock/haddock2.4-2021-01/Haddock/Main/ && \
    rm QueueSubmit.py && \
    cp QueueSubmit_concat.py QueueSubmit.py