FROM mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu16.04

ENV DEBIAN_FRONTEND noninteractive
USER root

## Set an working directory for the MMAE ML resources
WORKDIR /software

## Install essential for building
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    git \
    sudo \
    cmake \
    wget \
    flex \
    gfortran
    # \
    # python-pip \
    # python2.7 \
    # python2.7-dev

## Change bash Shell to tcsh
RUN sudo apt-get install tcsh && \
    chsh -s /bin/tcsh
    # chsh -s /usr/bin/tcsh
SHELL ["/bin/tcsh", "-c"]

## Install Azure ML Dependencies
RUN pip install --no-cache-dir \
    azureml-defaults \
    azureml-dataprep\
    azureml-core \
    azure-ml-api-sdk \
    azureml-train-automl-runtime

## Make software directory
# RUN mkdir software

## Install CNSsolve (http://cns-online.org/v1.3/)
COPY cns_solve_1.3_all_intel-mac_linux.tar.gz /software
RUN cd /software && \
    gunzip cns_solve_1.3_all_intel-mac_linux.tar.gz && \
    tar xvf cns_solve_1.3_all_intel-mac_linux.tar && \
    rm cns_solve_1.3/cns_solve_env
COPY cns_solve_env /software/cns_solve_1.3
RUN cd /software/cns_solve_1.3 && \
    make install

## Install FreeSASA
# RUN cd software && \
#     wget https://freesasa.github.io/freesasa-2.0.3.tar.gz && \
#     tar xvfz freesasa-2.0.3.tar.gz && \
#     cd freesasa-2.0.3 && \
#     ./configure --disable-json --disable-xml --prefix ~/software && \
#     make && \
#     make install

## Install HADDOCK (https://www.bonvinlab.org/software/haddock2.4/installation/)
COPY haddock2.4-2021-01.tgz /software
RUN cd /software && \
    tar xvfz haddock2.4-2021-01.tgz

## Configure HADDOCK
COPY local_config_file /software/haddock2.4-2021-01
RUN cd /software/haddock2.4-2021-01 && \
    ./install.csh local_config_file 
    #&& \
    #source haddock_configure.csh


    # export PFX=$HOME/haddock
    # export CNS=$PFX/cns_solve
    # mkdir -p $CNS
    # tar -C $CNS --strip-components=1 -xf cns_solve_1.3_all_intel-mac_linux.tar.gz
    # tar -C $PFX -xf haddock2.4-2022-01.tgz
    # pushd $CNS
    # sed -i.BACK -e "s|_CNSsolve_location_|$CNS|g" cns_solve_env
    # cp -a $PFX/haddock2.4-2022-01/cns1.3/* source
    # make install 2>&1|tee make-install.out
    # popd


